### ISSUE TITLE
Is there a way to adjust the strength of the background blur?

### ISSUE THREAD

**Issue by tthn0** [dizzyup/hyper-hypest#14]

**Comment by tthn0** [comment]
Adjusting vibrancyLevel still doesn't change the strength of the blur tho

**Comment by dizzyup** [comment]
@itstommi Sorry! That blur effect is handled at the operating system level - there's no way to override that setting in Electron.

**Comment by tthn0** [comment]
> @itstommi Sorry! That blur effect is handled at the operating system level - there's no way to override that setting in Electron.

Ohh I didn't know. Thanks for letting me know 👍
