### ISSUE TITLE
I don't have a vibrancy effect.

### ISSUE THREAD

**Issue by MomboteQ** [dizzyup/hyper-hypest#16]
Hello, i don't have a vibrancy effect. Help me please.
![Zrzut ekranu z 2020-12-27 14-15-34](https://user-images.githubusercontent.com/60738939/103171651-3cd25b80-484e-11eb-9657-6698b0d234f3.png)

**Comment by dizzyup** [comment]
@MombotTv I'm not too familiar with Linux, but looking around it seems like Electron might not support transparency effects on Linux? I could be wrong though - have you used any other Hyper themes that support transparency? Could you paste your hyper config here so I can double check?
