### ISSUE TITLE
Vibrancy disabled when window loses focus

### ISSUE THREAD

**Issue by nickcabral** [dizzyup/hyper-hypest#18]
Thanks for the great work, this is my favorite hyper theme! One question that I haven't been able to find the answer to: is there any way to retain vibrancy (transparency) when the hyper window loses focus?

Example when focused:
<img width="728" alt="image" src="https://user-images.githubusercontent.com/9586778/159699726-068dcc6f-821d-4e42-806c-07d2659d9e6f.png">
Example when focus lost (clicked outside of Hyper):
<img width="707" alt="image" src="https://user-images.githubusercontent.com/9586778/159699798-4f898f46-625f-4f9d-8b96-be293dce4ed9.png">

macOS 12.2.1, 12.3
Hyper 3.2.0
hyper-hypest 1.3.0; no other plugins installed

**Comment by ameliabruno** [comment]
same issue here

**Comment by amebru** [comment]
same issue here

macOS 13.2.1 (22D68)
Hyper 3.4.1 (stable)
hyper-hypest latest

**Comment by dizzyup** [comment]
I believe this is a macOS/Electron behavior that can't be overridden unfortunately - native windows on macOS also lose their vibrancy when they become inactive.
