### ISSUE TITLE
Vibrancy doesnt blur

### ISSUE THREAD

**Issue by ghost** [dizzyup/hyper-hypest#19]
Im on mac os 12, and my hyper version is 3.2.3.
<img width="1512" alt="Screenshot 2022-05-12 at 5 25 30 PM" src="https://user-images.githubusercontent.com/79365567/168069289-df78f847-1026-4956-8ea2-b341284ac48e.png">
for some reason, the window gets transparent, but its not blurring the background.

**Comment by ghost** [comment]
Alright so i just restarted my laptop and surprisingly the terminal blurs now.

**Comment by wilzone1384** [comment]
Helllo
