### ISSUE TITLE
Don't seeing text on tab

### ISSUE THREAD

**Issue by GeoffreyBrunet** [dizzyup/hyper-hypest#3]
Hello, thank you for this Hyper Theme, it's very nice ! I've juste a problem with the color when I use tab, I don't see text.
<img width="761" alt="Capture d’écran 2019-06-06 à 10 56 13" src="https://user-images.githubusercontent.com/25690819/59020299-fa02fa00-8849-11e9-9995-ab174e449394.png">

**Comment by dizzyup** [comment]
Hi @GeoffreyBrunet, sorry for the slow response - I just released [1.2.1](https://github.com/dizzyup/hyper-hypest/releases/tag/1.2.1) which addresses this bug when `vibrancy` is set to `false` (which fortunately I think you already have!) 🙂

There's a bit of background I've added to the readme that explains the underlying issue (and why I can only fix it in the non-vibrant versions of the themes for now).

**Comment by GeoffreyBrunet** [comment]
Yes it's perfect, thank you !
