### ISSUE TITLE
Pasted text unreadable due to black background

### ISSUE THREAD

**Issue by franciscovilchezv** [dizzyup/hyper-hypest#6]
When pasting a text in terminal, appears with a black background that makes it unreadable.   Using Catalina with zsh.

![Screen Shot 2020-01-12 at 2 31 14 PM](https://user-images.githubusercontent.com/9200906/72224395-31f0bf00-3548-11ea-93a2-910b3f9b992a.png)

**Comment by dizzyup** [comment]
@wilchess26 I'm afraid this is a known issue with a library that Hyper itself uses - https://github.com/dizzyup/hyper-hypest#issues-with-selection-colors-when-vibrancy-is-enabled

I'm keeping track of developments in the issues mentioned there but until then the only workaround I've seen is the one I've called out -

```
echo 'unset zle_bracketed_paste' >> ~/.zshrc
```
