### ISSUE TITLE
automatically switch

### ISSUE THREAD

**Issue by wellblink** [dizzyup/hyper-hypest#7]
How can I automatically switch between dark and light mode in macOS?

**Comment by dizzyup** [comment]
As far as I'm aware this isn't supported by Hyper itself, or at least by the version of Electron they're building on.

Would be nice functionality but for now the only way to switch between modes is to update the config: https://github.com/dizzyup/hyper-hypest#configuration

**Comment by wellblink** [comment]
> As far as I'm aware this isn't supported by Hyper itself, or at least by the version of Electron they're building on.
> 
> Would be nice functionality but for now the only way to switch between modes is to update the config: https://github.com/dizzyup/hyper-hypest#configuration

Oh!  Thank you!  Hope this feature comes soon!  I love this theme so much!

**Comment by dizzyup** [comment]
No problem - love to hear that!
